"""empty message

Revision ID: b8ebd254ae3d
Revises: 1e11c2f37f94
Create Date: 2020-10-29 13:09:24.740371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8ebd254ae3d'
down_revision = '1e11c2f37f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'category')
    op.drop_column('comments', 'time_posted')
    op.drop_column('comments', 'dislikes')
    op.drop_column('comments', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('time_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
